# Generated by Django 5.1.2 on 2024-11-21 00:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('players', models.IntegerField(help_text='Número de jugadores (debe ser mayor que 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('game_mode', models.CharField(choices=[('Presencial en Mesa', 'Presencial en Mesa'), ('Rol en Vivo', 'Rol en Vivo'), ('Online', 'Online')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Por Iniciar', 'Por Iniciar'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
